### ISSUE TITLE
Do not create links manually

### ISSUE THREAD

**Issue by harjot1singh** [ShabadOS/theme-tool#12]
src/components/editors/exportEditor.js `saveFile` function creates a document element and appends it to the DOM. 

React will have no idea about this, and so it's much better to dynamically render the link, or trigger the download another way.

**Comment by saihaj** [comment]
> Just don’t attach it to body https://stackoverflow.com/questions/31214677/download-a-reactjs-object-as-a-file
_Originally posted by @Harjot1Singh_ [View in Slack](https://shabados.slack.com/archives/D0117052YGG/p1589419955000300)

**Comment by saihaj** [comment]
resolution took 5 minutes
