### ISSUE TITLE
Enable offline-usage

### ISSUE THREAD

**Issue by harjot1singh** [ShabadOS/theme-tool#13]
Enabling the service worker would allow the app to work offline. Is this a good idea? Who knows.

**Comment by bhajneet** [comment]
I don't think we need this feature, personally speaking. I do get that it could be done -- just not sure how it helps much unless they already opened it once.

Rather, perhaps we would want them to have a way to download the theme tool as a separate app?

**Comment by saihaj** [comment]
I think GitHub Pages has a CDN. @Harjot1Singh do I need to do something about that or it will work as expected?
```
// Our service worker won't work if PUBLIC_URL is on a different origin
// from what our page is served on. This might happen if a CDN is used to
// serve assets; see https://github.com/facebook/create-react-app/issues/2374
```
