### ISSUE TITLE
Add button to match vertical and horizontal padding

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/theme-tool#15]
>  Layout > Vertical/Horizontal padding - the vertical padding should not be affecting horizontal. Either have a button that locks horizontal to match vertical (making horizontal padding not user-modifiable and automatically matching vertical padding slider) or split the two. I would recommend adding a "lock" button (on by default) or simply having one padding slider for vertical and horizontal padding. Lock button is preferable.

_Originally posted by @bhajneet in https://github.com/ShabadOS/theme-tool/pull/1#issuecomment-623015497_

This will allow fixing `NaN` on slider
> why does width come up as `NaN` initially?
<sub>[View in Slack](https://shabados.slack.com/archives/C013GFL7B0C/p1588957973044200)</sub>

Impact high because to match them one needs to get sliders same value and can be quite annoying.

**Comment by bhajneet** [comment]
Labelled as a fix, since this is an incorrect implementation, not a new feature/improvement

**Comment by bhajneet** [comment]
Use same unit when locked (e.g. "vh")

When unlocked, use respective units. E.g. Horizontal slider should use "vw" and the vertical slider should use "vh".

**Comment by saihaj** [comment]
I understand what you want but I need to think of way so that I don't break too many things and still implement this.
We can add a checkbox that will act as a lock button (checked means lock).
 
>Use same unit when locked (e.g. "vh")

So is it right to assume that if it locked then use "vh" ?

**Comment by bhajneet** [comment]
I think the top slider should probably be horizontal padding as so many
things specify width before height. I also believe that whatever unit is
used should be the first slider's unit (in this case horizontal = vw).
However I find it odd to use the larger step size of vw, so perhaps with
different step sizes we can use vw as the default.
