### ISSUE TITLE
Live Captions Customization (Overlay Theme Creator/Generator)

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/theme-tool#18]
Basically allowing manipulation of all fields in the current overlay theme files.

- [x] layout (top, left, bottom, full screen), dropdown. if left, slider for how much of the left
- [x] font sizes (master + primary/secondary relative sliders = 3 sliders in total, each secondary line must have some in-built font size relation to base off so .5 english = .6 punjabi or something and the secondary slider scales these appropriately)
- [x] center align toggle
- [x] padding sliders
- [x] background options: full (fills to the edge), box (fills the box around the words), lines (fills bg of only the words) dropdown

Color implies color and potentially opacity (rgba). So might be best to just do these all in rgb with separate opacity for the ones that need it.

- [x] Custom font colors for primary (gurbani) and secondary (all other) lines
- [x] Larrivaar assist color
- [x] Vishraam colors
- [x] Custom shadow colors for primary and secondary
- [x] Custom bg color

**Comment by saihaj** [comment]
Can you please check mark all the items that are done and probably open new issues or link any open
