### ISSUE TITLE
Add ratio option in preview tab

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/theme-tool#2]
Add "ratio" option to "Preview" tab, which allows 16:9 (horizontal), 9:16 (vertical), 18:9, 21:9, and 4:3 options in the dropdown

_Originally posted by @bhajneet in https://github.com/ShabadOS/theme-tool/pull/1#issuecomment-621974197_

**Comment by bhajneet** [comment]
Perhaps adding something like this can help https://github.com/globaljake/react-resize-to-aspect-ratio
