### ISSUE TITLE
Overlay text should not use "vh"

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/theme-tool#25]
The text doesn't scale horizontally right now because we are using "vh". Need to find a solution that will work for vertically and horizontally.

**Comment by bhajneet** [comment]
My initial thought is this will also have to be calculated by JS and then converted for variables in export

**Comment by saihaj** [comment]
What should be calculated?

**Comment by bhajneet** [comment]
Since vh is a percentage of the height of the viewport, we want to simulate
that by using a percentage of the height of the overlay aspect ratio
container. This percentage can be converted into px for render, but saved
as percent in slider, and exported as that percent number in vh units.

**Comment by bhajneet** [comment]
@Harjot1Singh could you share the resolution in this thread please? I'm curious how it was resolved

**Comment by saihaj** [comment]
While we were working on aspect ratio #2 had to do something about scaling the overlay part (padding and text) so as suggested above we came up with a factor for `vh`and `vw` which resolves this issue.
