### ISSUE TITLE
Width of overlay and horizontal padding

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/theme-tool#36]
**Describe the bug**
Changing horizontal padding is causing an issue with calculation for width.

**Screenshots**
![issue](https://user-images.githubusercontent.com/14130567/84091392-41264c80-a9c2-11ea-9641-012fe8a95faf.gif)

**Comment by saihaj** [comment]
Need to check the css variables in `options.js` and compare in `Preview.css`

**Comment by harjot1singh** [comment]
`overlay-width` is wrong/short.

**Comment by harjot1singh** [comment]
@saihaj solution is to use `box-sizing: border-box`, I think you were manually trying to calculate the width based on the padding.
