### ISSUE TITLE
Slider issues

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/theme-tool#38]
**Describe the bug**
I set the padding slider in the window tab. Changing other settings will make the padding go to 0 in the preview pane unless user "taps" or "clicks" on the circle of the slider for the window tab's padding.

**Screenshots**
![issue](https://user-images.githubusercontent.com/14130567/84092238-c7439280-a9c4-11ea-9889-65c76b35f6cd.gif)

**Comment by saihaj** [comment]
Whenever changes are made those are written as CSS vars to the DOM and saved to localStorage. Any idea @Harjot1Singh why could this be happing? 

Note: this is working fine on `dev` at 6438600e509b081d8beb84ee19bdfee15619da7e and is introduced by #35. I guess we need to make some changes to the reducer there.

**Comment by harjot1singh** [comment]
Yeah it could be that the check for whether the required properties have been filled in are not being done properly or returning the correct value

**Comment by harjot1singh** [comment]
It was actually fixed when I just fixed the bug which incorrectly sets the slider values to the same as the overlay horizontal padding.
