### ISSUE TITLE
Add toggle in preview tab to hide background image and replace with "checkerboard transparent" pattern

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/theme-tool#39]
Something like this but with lighter gray instead of black: https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/10x10_checkered_board_transparent.svg/500px-10x10_checkered_board_transparent.svg.png

**Comment by saihaj** [comment]
instead of setting the background image in css we can do it from component and then just have a toggle to change the image

**Comment by saihaj** [comment]
Is this fine?
![checkboard](https://user-images.githubusercontent.com/44710980/84707234-f8bbe100-af23-11ea-9216-c65bfaa140da.png)

**Comment by bhajneet** [comment]
Yes, that should be good
