### ISSUE TITLE
Overlay > Justification renders incorrectly

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/theme-tool#40]
**Screenshots**
![issue](https://user-images.githubusercontent.com/14130567/84093161-72ede200-a9c7-11ea-8702-b56a53408873.gif)

**Comment by saihaj** [comment]
What is expected outcome?

**Comment by bhajneet** [comment]
Middle should put the line in the middle, bottom should show it at the bottom. It is possible to test these options with Example.CSS file in Shabad OS desktop

**Comment by saihaj** [comment]
@Harjot1Singh help me please 🙏

**Comment by harjot1singh** [comment]
The issue comes from height -> 100 not really being such. Will PR.
