### ISSUE TITLE
Style of export tab doesn't match the rest

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/theme-tool#41]
**Describe the bug**
Export tab doesn't have "pane" class

**Screenshots**
Pane:
![image](https://user-images.githubusercontent.com/14130567/84093366-03c4bd80-a9c8-11ea-9c7b-b12970025918.png)

No Pane:
![image](https://user-images.githubusercontent.com/14130567/84093352-f90a2880-a9c7-11ea-8477-567fb365343a.png)

**Comment by saihaj** [comment]
Since export pane is its own component rather than a dynamically rendered component. Will need to make some changes in `Editors/exportEditor.js` to include that `className`
