### ISSUE TITLE
Adjust padding between items

### ISSUE THREAD

**Issue by harjot1singh** [ShabadOS/theme-tool#57]
**Is your feature request related to a problem? Please describe.**
The secondary lines have the same line spacing, even if a different field. This makes it hard to read.

**Describe the solution you'd like**
Toggle the padding between items. Perhaps even differentiate between primary and secondary text padding.

**Describe alternatives you've considered**
- Modifying CSS by hand: too much effort
- Living with it: hard to read
- Limiting to one secondary text field: ok for most cases, but sometimes you may want both

Needs screenshot + rewording

**Comment by bhajneet** [comment]
There is no assignee or method for completing work
