### ISSUE TITLE
Interactive tutorials

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/theme-tool#58]
**Is your feature request related to a problem? Please describe.**
Interactive tutorials to help users get started. It will make it more immersive user experience 

**Describe the solution you'd like**
Something like this: https://www.npmjs.com/package/react-interactive-tutorials

**Describe alternatives you've considered**
Documented steps like tutorials.shabados.com are good but sometimes you just want to get started without reading things but to still want to know somewhat.

**Comment by bhajneet** [comment]
Too difficult to interactively guide user to download and place a file in their file explorer. This would also be a lot of time and effort for a very low impact improvement/feature.
