### ISSUE TITLE
Ability to name themes

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/theme-tool#9]
> Exporting would be even nicer if we could type the name of the theme before creating a file name.
_Originally posted by @bhajneet in https://github.com/ShabadOS/theme-tool/pull/1#issuecomment-623015497_

**Comment by saihaj** [comment]
> default should be a 3 random words to avoid any conflicts https://www.npmjs.com/package/random-words
_Originally posted by @bhajneet on WhatsApp_

**Comment by saihaj** [comment]
@bhajneet do we want random words?

**Comment by bhajneet** [comment]
the field to customize the name of the overlay file should be pre-populated with something random that is also somewhat easy to recognize

**Comment by bhajneet** [comment]
can that pre-populated field also change (if not user-modified) on each click of the export button?

**Comment by saihaj** [comment]
Decided to go with timestamps. Default name format:
> Overlay 2020-05-21 HH_MM_SS
_Origanlly posted by @bhajneet on Slack_
